name: wolf

networks:
  wolf:
    driver: bridge

volumes:
  nats-data:
  minio-data:
  tempo-data:
  grafana-data:
  prometheus-data:
  pg-data:

services:
  nats:
    image: nats:2.12.4
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ${WOLF_DIR}/deploy/config/jetstream/nats.conf:/etc/nats/nats.conf:ro
      - nats-data:/data/jetstream
    networks: [wolf]

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data
    networks: [wolf]

  tempo:
    image: grafana/tempo:2.9.1
    command:
      - "--config.file=/etc/tempo/tempo.yaml"
      - "-config.expand-env=true"
    environment:
      TEMPO_S3_BUCKET: tempo-traces
      TEMPO_S3_ENDPOINT: minio:9000
      TEMPO_S3_ACCESS_KEY: minioadmin
      TEMPO_S3_SECRET_KEY: minioadmin123
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ${WOLF_DIR}/deploy/config/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/tmp/tempo
    networks: [wolf]

  prometheus:
    image: prom/prometheus:v3.9.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    ports:
      - "9095:9090"
    volumes:
      - ${WOLF_DIR}/deploy/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks: [wolf]

  grafana:
    image: grafana/grafana:12.3
    ports:
      - "3000:3000"
    environment:
      PROMETHEUS_HOST: ${VM_IP}
      PROMETHEUS_PORT: 9095
      TEMPO_HOST: ${VM_IP}
      TEMPO_PORT: 3200
    volumes:
      - grafana-data:/var/lib/grafana
      - ${WOLF_DIR}/deploy/config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - tempo
    networks: [wolf]

  alloy:
    image: grafana/alloy:v1.12.2
    command: ["run", "/etc/alloy/alloy.hcl"]
    environment:
      ALLOY_LOG_LEVEL: debug
      TEMPO_OTLP_ENDPOINT: tempo:4317
      PROM_REMOTE_WRITE_URL: http://prometheus:9090/api/v1/write
    ports:
      - "8085:8085"
      - "8086:8086"
    volumes:
      - ${WOLF_DIR}/deploy/config/alloy/alloy.hcl:/etc/alloy/alloy.hcl:ro
    depends_on:
      - tempo
      - prometheus
    networks: [wolf]

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: wolf
      POSTGRES_PASSWORD: wolf123
      POSTGRES_DB: wolf
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql
    networks: [wolf]
