apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://$PROMETHEUS_HOST:$PROMETHEUS_PORT
    uid: prometheus-main
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://$TEMPO_HOST:$TEMPO_PORT
    editable: true
    uid: tempo-main