apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.2.101:9095
    uid: prometheus-main
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://192.168.2.101:3200
    editable: true
    uid: tempo-main